name: motiv8tor
version: 0.1.0+1
description: An app to motivate you

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  fluttertoast: ^8.0.8
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  numberpicker: ^2.1.1
  awesome_notifications: ^0.6.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/awesome-notifications-logo-color.png
    - assets/images/awesome-notifications-logo-black.png
    - assets/images/awesome-notifications-logo-white.png
    - assets/images/animated-bell.gif
    - assets/images/placeholder.gif
    - assets/images/happy-dogs.jpg
    - assets/images/balloons-in-sky.jpg
    - assets/images/android-bg-worker.jpg
    - assets/images/fireman-hero.jpg
    - assets/images/delivery.jpeg
    - assets/images/melted-clock.png
    - assets/images/rock-disc.jpg
    - assets/images/classic-disc.jpg
    - assets/images/dj-disc.jpg
    - assets/images/80s-disc.jpg
    - assets/images/remix-disc.jpg
    - assets/images/old-disc.jpg
